name: "Delete CloudFormation Stack on PR Merge"

on:
  pull_request:
    types: [closed]
    paths:
      - "cloudformation/**"

jobs:
  cleanup_on_merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Delete CloudFormation Test Stack
        run: |
          stack_name="pr-test-stack-${{ github.event.pull_request.number }}"

          aws cloudformation delete-stack --stack-name $stack_name
          echo "Deleted CloudFormation stack: $stack_name"
