name: "Validate CloudFormation Template on PR"

on:
  pull_request:
    paths:
      - "cloudformation/**"

permissions:
  contents: write
  pull-requests: read

jobs:
  validate_cfn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template --template-body file://cloudformation/s3-bucket.yaml

      - name: Deploy CloudFormation Stack
        run: |
          stack_name="pr-test-stack-${{ github.event.pull_request.number }}"
          aws cloudformation create-stack \
            --stack-name $stack_name \
            --template-body file://cloudformation/s3-bucket.yaml \
            --parameters ParameterKey=Environment,ParameterValue=test

      - name: Comment on the PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `CloudFormation test stack has successfully been deployed for this PR. Stack Name: pr-test-stack-${{ github.event.pull_request.number }}`
            })

  cleanup_on_merge:
    runs-on: ubuntu-latest
    needs: validate_cfn
    if: github.event.pull_request.merged == true

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Delete CloudFormation Test Stack
        run: |
          stack_name="pr-test-stack-${{ github.event.number }}"
          aws cloudformation delete-stack --stack-name $stack_name